### ISSUE TITLE
Joystick Steuerung Verbessern

### ISSUE THREAD

**Issue by 0xChri2** [ImChri2/ESPHSNR2022-23#8]
Durch das Arbeiten mit Vektoren könnte die Joystick Steuerung besser werden

**Comment by derLesh** [comment]
Um eine Idee zu bekommen wie ein Joystick gut umzusetzen ist, kann man sich den Aufbau/die Verarbeitung von einem N64 Controller angucken

https://ultra64.ca/files/documentation/online-manuals/man/pro-man/pro26/index26.2.html
